name: CI

on:
  push:
    branches: [ '**' ]

jobs:
  container_build:
    name: Build and Push Docker Container
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . -t chrisjohnson00/qbittorrent-openvpn:${GITHUB_REF##*/}
    - name: Login to docker hub
      run: docker login --username=chrisjohnson00 --password=${{ secrets.DOCKER_HUB_PASSWORD }}
    - name: Push the Docker image
      run: docker push chrisjohnson00/qbittorrent-openvpn:${GITHUB_REF##*/}
  actionslint:
    name: 'Actions Yaml Lint'
    runs-on: ubuntu-18.04
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
      - name: 'Actions Yaml Lint'
        uses: karancode/yamllint-github-action@v2.0.0
        with:
          yamllint_file_or_dir: '.github/workflows'
          yamllint_comment: true
          yamllint_config_filepath: '.yamllint'
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
